;;
;; STKOBJ7.SC
;;
;; This file contains SCI representations of all objects found in the server's
;; object class data files.  This file was generated by the SPARCStation server
;; and is maintained by the SPARCStation server.  You SHOULD NOT manually
;; modify this file for ANY reason.  The system will most probably cease
;; to function if you did.
;;
;; Author: SPARCStation (Sat Dec  2 23:35:47 2017)
;;

(module# STOCKOBJ7)

(public StockObjInitter7 0)
(define StockObjList (ModuleID STOCKOBJ0 0))

(include "wobject.sh")

(instance SOBJGreenCrystalD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenCrystalD", 
			pName: "Green Crystal",
			loop: 0,
			pBaseView: 2803,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJGreenCrystalE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenCrystalE", 
			pName: "Green Crystal",
			loop: 0,
			pBaseView: 2804,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJGreenCrystalF of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenCrystalF", 
			pName: "Green Crystal",
			loop: 0,
			pBaseView: 2805,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJGreenCrystalG of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenCrystalG", 
			pName: "Green Crystal",
			loop: 0,
			pBaseView: 2806,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorA", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2880,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorB", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2881,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorC", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2882,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorD", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2883,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorE", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2884,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorF of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorF", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2980,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorG of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorG", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2981,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorH of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorH", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2982,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJCellFloorI of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CellFloorI", 
			pName: "Floor Tile",
			loop: 0,
			pBaseView: 2983,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
			pPolygon: -1,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJGreenWaterA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenWaterA", 
			pName: "Green Water",
			loop: 0,
			pBaseView: 2892,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJGreenWaterB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenWaterB", 
			pName: "Green Water",
			loop: 0,
			pBaseView: 2893,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJGreenWaterC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenWaterC", 
			pName: "Green Water",
			loop: 0,
			pBaseView: 2894,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJGreenWaterD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenWaterD", 
			pName: "Green Water",
			loop: 0,
			pBaseView: 2899,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaA", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2992,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaB", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2993,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaC", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2994,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaD", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2999,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaE", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2835,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaF of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaF", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2836,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJLavaG of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "LavaG", 
			pName: "Lava",
			loop: 0,
			pBaseView: 2838,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 32,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)
	)
)

(instance SOBJYellowShroomA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "YellowShroomA", 
			pName: "Yellow Mushroom",
			loop: 0,
			pBaseView: 2813,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJYellowShroomB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "YellowShroomB", 
			pName: "Yellow Mushroom",
			loop: 0,
			pBaseView: 2814,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJYellowShroomC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "YellowShroomC", 
			pName: "Yellow Mushroom",
			loop: 0,
			pBaseView: 2815,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJYellowShroomD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "YellowShroomD", 
			pName: "Yellow Mushroom",
			loop: 0,
			pBaseView: 2816,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJEnidStatue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "EnidStatue", 
			pName: "Statue of Enid",
			loop: 0,
			pBaseView: 3289,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJDuachStatue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "DuachStatue", 
			pName: "Statue of Duach",
			loop: 0,
			pBaseView: 3269,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJEnidBackArch of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "EnidBackArch", 
			pName: "Door",
			loop: 0,
			pBaseView: 2833,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1024,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BEntry)
	)
)

(instance SOBJEnidBackDoor of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "EnidBackDoor", 
			pName: "Door",
			loop: 0,
			pBaseView: 62450,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1040,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BEntry)

		(aWhatObj addBase: BOpenable)
	)
)

(instance SOBJDespothesStatue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "DespothesStatue", 
			pName: "Statue of Despothes",
			loop: 0,
			pBaseView: 3259,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJElphameStatue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "ElphameStatue", 
			pName: "Statue of Elphame",
			loop: 0,
			pBaseView: 3279,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJFinvarraStatue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "FinvarraStatue", 
			pName: "Statue of Finvarra",
			loop: 0,
			pBaseView: 3299,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJMabonStatue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MabonStatue", 
			pName: "Statue of Mabon",
			loop: 0,
			pBaseView: 3309,
			pAction: 0,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 0,
			pBaseBitsHi: 0,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))
	)
)

(instance SOBJSentinelBaldric of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SentinelBaldric", 
			pName: "Sentinel's Baldric",
			loop: 0,
			pBaseView: 10900,
			pAction: 29,
			pClutStart: 11,
			pColor: 54,
			pBaseBitsLo: 2057,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 80,
			pAreaWorn: 99,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJImplementorBaldric of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "ImplementorBaldric", 
			pName: "Implementor's Baldric",
			loop: 0,
			pBaseView: 10900,
			pAction: 29,
			pClutStart: 11,
			pColor: 98,
			pBaseBitsLo: 2057,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 80,
			pAreaWorn: 99,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJEventsBaldric of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "EventsBaldric", 
			pName: "Event Host's Baldric",
			loop: 0,
			pBaseView: 10900,
			pAction: 29,
			pClutStart: 11,
			pColor: 88,
			pBaseBitsLo: 9,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 80,
			pAreaWorn: 99,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)
	)
)

(instance SOBJMentorBaldric of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MentorBaldric", 
			pName: "Mentor's Baldric",
			loop: 0,
			pBaseView: 10900,
			pAction: 29,
			pClutStart: 11,
			pColor: 49,
			pBaseBitsLo: 9,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 80,
			pAreaWorn: 99,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)
	)
)

(instance SOBJGameOfficial of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GameOfficial", 
			pName: "Mythril Helmet",
			pIDName: "Game Officials",
			loop: 0,
			pBaseView: 30100,
			pAction: 29,
			pClutStart: 63,
			pColor: 83,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSentinelHelm of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SentinelHelm", 
			pName: "Game Officials",
			pIDName: "Sentinel's Helmet",
			loop: 0,
			pBaseView: 31500,
			pAction: 29,
			pClutStart: 63,
			pColor: 83,
			pBaseBitsLo: 2057,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJMentorHelmet of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MentorHelmet", 
			pName: "Mythril Helmet",
			pIDName: "Guide's Helmet",
			loop: 0,
			pBaseView: 31550,
			pAction: 29,
			pClutStart: 63,
			pColor: -1,
			pBaseBitsLo: 2057,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 25,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJBishopHat of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "BishopHat", 
			pName: "Game Officials",
			pIDName: "Bishop's Hat",
			loop: 0,
			pBaseView: 31600,
			pAction: 29,
			pClutStart: 63,
			pColor: 83,
			pBaseBitsLo: 2057,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJDuachsAura of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "DuachsAura", 
			pName: "Game Officials",
			pIDName: "Duach's Aura",
			loop: 0,
			pBaseView: 31650,
			pAction: 29,
			pClutStart: 63,
			pColor: 83,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJDespothesCrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "DespothesCrown", 
			pName: "Game Officials",
			pIDName: "Despothes' Crown",
			loop: 0,
			pBaseView: 31700,
			pAction: 29,
			pClutStart: 63,
			pColor: 83,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJRareCrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RareCrown", 
			pName: "Game Officials",
			pIDName: "Implementor's Crown",
			loop: 0,
			pBaseView: 31400,
			pAction: 29,
			pClutStart: 63,
			pColor: 83,
			pBaseBitsLo: 2057,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJHairDye of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "HairDye", 
			pName: "Bottle of Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: -1,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 1,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightRed of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightRed", 
			pName: "Bottle of Light Red Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 59,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 1,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdRed of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdRed", 
			pName: "Bottle of Red Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 58,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 2,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightGrey of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightGrey", 
			pName: "Bottle of Light Grey Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 100,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 3,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdGrey of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdGrey", 
			pName: "Bottle of Grey Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 99,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 4,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdDarkGrey of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdDarkGrey", 
			pName: "Bottle of Dark Grey Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 98,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 5,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdOrange of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdOrange", 
			pName: "Bottle of Orange Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 89,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 6,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightOrange of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightOrange", 
			pName: "Bottle of Light Orange Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 90,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 7,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdReddishBrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdReddishBrown", 
			pName: "Bottle of Reddish Brown Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 105,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 8,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdBrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdBrown", 
			pName: "Bottle of Brown Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 104,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 9,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightYellow of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightYellow", 
			pName: "Bottle of Light Yellow Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 64,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 10,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdYellow of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdYellow", 
			pName: "Bottle of Yellow Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 63,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 11,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightBlue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightBlue", 
			pName: "Bottle of Light Blue Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 54,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 12,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdBlue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdBlue", 
			pName: "Bottle of Blue Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 53,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 13,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdWhite of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdWhite", 
			pName: "Bottle of White Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 43,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 14,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdOlive of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdOlive", 
			pName: "Bottle of Olive Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 48,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 15,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightOlive of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightOlive", 
			pName: "Bottle of Light Olive Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 49,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 16,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdMagenta of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdMagenta", 
			pName: "Bottle of Magenta Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 68,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 17,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightMagenta of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightMagenta", 
			pName: "Bottle of Light Magenta Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 69,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 18,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdDarkBrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdDarkBrown", 
			pName: "Bottle of Dark Brown Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 73,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 19,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightBrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightBrown", 
			pName: "Bottle of Light Brown Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 74,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 20,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdAqua of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdAqua", 
			pName: "Bottle of Aqua Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 78,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 21,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightAqua of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightAqua", 
			pName: "Bottle of Light Aqua Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 79,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 22,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdGreen of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdGreen", 
			pName: "Bottle of Green Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 83,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 23,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightGreen of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightGreen", 
			pName: "Bottle of Light Green Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 84,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 24,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdPurple of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdPurple", 
			pName: "Bottle of Purple Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 93,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 25,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdLightPurple of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdLightPurple", 
			pName: "Bottle of Light Purple Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 94,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 26,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdPaleBrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdPaleBrown", 
			pName: "Bottle of Pale Brown Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 106,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 27,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJhdPalePaleBrown of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "hdPalePaleBrown", 
			pName: "Bottle of Pale Pale Brown Hair Dye",
			loop: 0,
			pBaseView: 51550,
			pAction: 29,
			pClutStart: 68,
			pColor: 107,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BDye)
			pHairDye: 28,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)
	)
)

(instance SOBJBaseDingo of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "BaseDingo", 
			pName: "Dingo",
			loop: 2,
			pBaseView: 40300,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 15,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJDingoPup of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "DingoPup", 
			pName: "Dingo Puppy",
			loop: 2,
			pBaseView: 40300,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 15,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJCTCHorn of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CTCHorn", 
			pName: "Call to Conflict Horn",
			loop: 0,
			pBaseView: 59900,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 10,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJRibbon of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Ribbon", 
			pName: "Ribbon",
			loop: 0,
			pBaseView: 59901,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJBlueRibbon of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "BlueRibbon", 
			pName: "Blue Ribbon",
			loop: 0,
			pBaseView: 59901,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJRedRibbon of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RedRibbon", 
			pName: "Red Ribbon",
			loop: 0,
			pBaseView: 59902,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWhiteRibbon of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WhiteRibbon", 
			pName: "White Ribbon",
			loop: 0,
			pBaseView: 59951,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJGreenRibbon of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GreenRibbon", 
			pName: "Green Ribbon",
			loop: 0,
			pBaseView: 59903,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJYellowRibbon of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "YellowRibbon", 
			pName: "Yellow Ribbon",
			loop: 0,
			pBaseView: 59950,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJGMCTCHorn of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GMCTCHorn", 
			pName: "Call to Conflict Horn Store",
			loop: 0,
			pBaseView: 59900,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 2049,
			pBaseBitsHi: 192,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BDye)
			pHairDye: 0,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 10,
		)

		(aWhatObj addBase: BDescribed)

		(aWhatObj addBase: BShop)
	)
)

(instance SOBJMistCreature of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MistCreature", 
			pName: "Mist Creature",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 84,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMistSpy of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MistSpy", 
			pName: "Seeker",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 84,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1800,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJServant of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Servant", 
			pName: "Servant of the Mists",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 84,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 20300,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJApophis of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Apophis", 
			pName: "Apophis",
			loop: 2,
			pBaseView: 41500,
			pAction: 1,
			pClutStart: -1,
			pColor: 100,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 3,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 10000,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJBerserker of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Berserker", 
			pName: "Berserker",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 20500,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWizardNPC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WizardNPC", 
			pName: "Wizard",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 2250,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWizardGuardNPC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WizardGuardNPC", 
			pName: "Guard",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJEvilWizard of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "EvilWizard", 
			pName: "Warlock",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 2400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJGoodWizard of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "GoodWizard", 
			pName: "Ancient One",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 2400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJNeutralWizard of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "NeutralWizard", 
			pName: "Mist Mage",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 2400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJEvilMinion of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "EvilMinion", 
			pName: "Evil Minion",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 9900,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJChampion of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Champion", 
			pName: "Champion",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 9900,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJProtector of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Protector", 
			pName: "Protector",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 9900,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJDireWolf of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "DireWolf", 
			pName: "Dire Wolf",
			loop: 2,
			pBaseView: 40300,
			pAction: 1,
			pClutStart: -1,
			pColor: 770,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 6,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJBerserkerMed of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "BerserkerMed", 
			pName: "Berserker",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 13000,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJPaladin of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Paladin", 
			pName: "Paladin",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3450,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJPaladinA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "PaladinA", 
			pName: "Paladin",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 4950,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJPaladinB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "PaladinB", 
			pName: "Paladin",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 6450,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJBaseWarden of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "BaseWarden", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA06 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA06", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3000,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA07 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA07", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3200,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA08 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA08", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA09 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA09", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3600,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA10 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA10", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3800,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA11 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA11", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 4000,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJWardenHA12 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "WardenHA12", 
			pName: "Warden",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 4200,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSoldier of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Soldier", 
			pName: "Base Soldier",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 12750,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSoldierE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SoldierE", 
			pName: "Soldier",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 12900,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSoldierN of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SoldierN", 
			pName: "Soldier",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 12900,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSoldierG of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SoldierG", 
			pName: "Soldier",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 16,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 12900,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJRandomMistGemD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RandomMistGemD", 
			pName: "Mist Talisman",
			loop: 0,
			pBaseView: 50850,
			pAction: 29,
			pClutStart: 54,
			pColor: 40,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJRandomMistGemC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RandomMistGemC", 
			pName: "Mist Talisman",
			loop: 0,
			pBaseView: 50850,
			pAction: 29,
			pClutStart: 54,
			pColor: 40,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJRandomMistGemB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RandomMistGemB", 
			pName: "Mist Talisman",
			loop: 0,
			pBaseView: 50850,
			pAction: 29,
			pClutStart: 54,
			pColor: 40,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJRandomMistGemA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RandomMistGemA", 
			pName: "Mist Talisman",
			loop: 0,
			pBaseView: 50850,
			pAction: 29,
			pClutStart: 54,
			pColor: 40,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJMinotaurTreasureB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurTreasureB", 
			pName: "Mist Talisman",
			loop: 0,
			pBaseView: 50850,
			pAction: 29,
			pClutStart: 54,
			pColor: 40,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJMinotaurTreasureA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurTreasureA", 
			pName: "Mist Talisman",
			loop: 0,
			pBaseView: 50850,
			pAction: 29,
			pClutStart: 54,
			pColor: 40,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJMinotaurGuard of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurGuard", 
			pName: "Aegiscian",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 3000,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurSoul of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurSoul", 
			pName: "Minotaur Soul Orb",
			loop: 0,
			pBaseView: 63150,
			pAction: 29,
			pClutStart: 94,
			pColor: 94,
			pBaseBitsLo: 8225,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BConsume)
			pState: _STATE_SOLID, 
		)
	)
)

(instance SOBJMinotaurSoulA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurSoulA", 
			pName: "Dolus Thrall Heart",
			loop: 0,
			pBaseView: 63150,
			pAction: 29,
			pClutStart: 94,
			pColor: 63,
			pBaseBitsLo: 8225,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BConsume)
			pState: _STATE_SOLID, 
		)
	)
)

(instance SOBJMinotaurSoulB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurSoulB", 
			pName: "Uplander Drudge Heart",
			loop: 0,
			pBaseView: 63150,
			pAction: 29,
			pClutStart: 94,
			pColor: 89,
			pBaseBitsLo: 8225,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BConsume)
			pState: _STATE_SOLID, 
		)
	)
)

(instance SOBJMinotaurSoulC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurSoulC", 
			pName: "Kamirian Invader Heart",
			loop: 0,
			pBaseView: 63150,
			pAction: 29,
			pClutStart: 94,
			pColor: 99,
			pBaseBitsLo: 8225,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BConsume)
			pState: _STATE_SOLID, 
		)
	)
)

(instance SOBJMinotaurSoulD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurSoulD", 
			pName: "Avalonian Heart",
			loop: 0,
			pBaseView: 63150,
			pAction: 29,
			pClutStart: 94,
			pColor: 100,
			pBaseBitsLo: 8225,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BConsume)
			pState: _STATE_SOLID, 
		)
	)
)

(instance SOBJMinotaurSoulE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurSoulE", 
			pName: "Saurilian Warrior Heart",
			loop: 0,
			pBaseView: 63150,
			pAction: 29,
			pClutStart: 94,
			pColor: 98,
			pBaseBitsLo: 8225,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BConsume)
			pState: _STATE_SOLID, 
		)
	)
)

(instance SOBJBaseMinotaur of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "BaseMinotaur", 
			pName: "Minotaur",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 0,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurWarrior of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurWarrior", 
			pName: "Minotaur",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 0,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurMage of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurMage", 
			pName: "Minotaur",
			loop: 2,
			pBaseView: 42300,
			pAction: 1,
			pClutStart: -1,
			pColor: 0,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurWarriorA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurWarriorA", 
			pName: "Dolus Thrall",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 57,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurWarriorB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurWarriorB", 
			pName: "Uplander Drudge",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 56,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurWarriorC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurWarriorC", 
			pName: "Kamirian Invader",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 54,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurWarriorD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurWarriorD", 
			pName: "Avalonian",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 55,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurWarriorE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurWarriorE", 
			pName: "Saurilian Warrior",
			loop: 2,
			pBaseView: 42200,
			pAction: 1,
			pClutStart: -1,
			pColor: 58,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurMageA of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurMageA", 
			pName: "Dolus Acolyte",
			loop: 2,
			pBaseView: 42300,
			pAction: 1,
			pClutStart: -1,
			pColor: 59,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurMageB of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurMageB", 
			pName: "Drudge Cleric",
			loop: 2,
			pBaseView: 42300,
			pAction: 1,
			pClutStart: -1,
			pColor: 60,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurMageC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurMageC", 
			pName: "Kamirian Druid",
			loop: 2,
			pBaseView: 42300,
			pAction: 1,
			pClutStart: -1,
			pColor: 61,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurMageD of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurMageD", 
			pName: "Avalonian Wizard",
			loop: 2,
			pBaseView: 42300,
			pAction: 1,
			pClutStart: -1,
			pColor: 62,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJMinotaurMageE of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "MinotaurMageE", 
			pName: "Saurilian Necromancer",
			loop: 2,
			pBaseView: 42300,
			pAction: 1,
			pClutStart: -1,
			pColor: 63,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 20,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSNSWeb1 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSWeb1", 
			pName: "Web",
			loop: 0,
			pBaseView: 2790,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)
	)
)

(instance SOBJSNSWeb2 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSWeb2", 
			pName: "Web",
			loop: 0,
			pBaseView: 2791,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)
	)
)

(instance SOBJSNSWeb3 of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSWeb3", 
			pName: "Web",
			loop: 0,
			pBaseView: 2792,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 5,
			pWeight: 5,
		)
	)
)

(instance SOBJSNSSkull of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSSkull", 
			pName: "Skull",
			loop: 0,
			pBaseView: 2901,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 10,
			pWeight: 10,
		)
	)
)

(instance SOBJSNSAltar of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSAltar", 
			pName: "Altar",
			loop: 0,
			pBaseView: 62050,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 50,
		)
	)
)

(instance SOBJSNSTorch of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSTorch", 
			pName: "Torch",
			loop: 0,
			pBaseView: 61800,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 33,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 30,
		)
	)
)

(instance SOBJSNSFountain of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSFountain", 
			pName: "Fountain",
			loop: 0,
			pBaseView: 54750,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 33,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCycle)
			pCycleSpeed: 6,
			pCycleType: 0,
			doit:,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 80,
		)
	)
)

(instance SOBJSNSMushroom of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSMushroom", 
			pName: "Mushroom",
			loop: 2,
			pBaseView: 61900,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 65,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BSit)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 50,
		)
	)
)

(instance SOBJSNSSittingRock of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSSittingRock", 
			pName: "Sitting Rock",
			loop: 0,
			pBaseView: 56200,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 65,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BSit)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 60,
		)
	)
)

(instance SOBJSNSStool of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSStool", 
			pName: "Stool",
			loop: 2,
			pBaseView: 62550,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 65,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BSit)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 20,
		)
	)
)

(instance SOBJSNSChair of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSChair", 
			pName: "Chair",
			loop: 2,
			pBaseView: 60500,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 65,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BSit)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 20,
		)
	)
)

(instance SOBJSNSStoneBench of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSStoneBench", 
			pName: "Stone Bench",
			loop: 2,
			pBaseView: 62100,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 65,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BSit)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 40,
		)
	)
)

(instance SOBJSNSBasket of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSBasket", 
			pName: "Basket",
			loop: 0,
			pBaseView: 55700,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 19,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BContainer)
			pWeightCap: 500,
			pBulkCap: 500,
		)

		(aWhatObj addBase: BOpenable)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 20,
			pWeight: 30,
		)
	)
)

(instance SOBJSNSDresser of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSDresser", 
			pName: "Dresser",
			loop: 0,
			pBaseView: 55800,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 19,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BContainer)
			pWeightCap: 1250,
			pBulkCap: 500,
		)

		(aWhatObj addBase: BOpenable)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BCarryable)
			pBulk: 40,
			pWeight: 70,
		)
	)
)

(instance SOBJSNSStorage of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSStorage", 
			pName: "Storage Box",
			loop: 0,
			pBaseView: 55100,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 19,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BOpenable)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BContainer)
			pWeightCap: 2000,
			pBulkCap: 1000,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 40,
			pWeight: 70,
		)
	)
)

(instance SOBJSNSCloset of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSCloset", 
			pName: "Closet",
			loop: 0,
			pBaseView: 55600,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 19,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BOpenable)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BContainer)
			pWeightCap: 2500,
			pBulkCap: 2500,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 40,
			pWeight: 70,
		)
	)
)

(instance SOBJSNSBigStrongBox of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "SNSBigStrongBox", 
			pName: "Strong Box",
			loop: 0,
			pBaseView: 55500,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 19,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BOpenable)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BContainer)
			pWeightCap: 12500,
			pBulkCap: 5000,
		)

		((aWhatObj addBase: BCarryable)
			pBulk: 40,
			pWeight: 100,
		)
	)
)

(instance SOBJCopperShop of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "CopperShop", 
			pName: "Eldrin",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 106,
			pBaseBitsLo: 6210,
			pBaseBitsHi: 68,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1200,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BShop)

		(aWhatObj addBase: BTalk)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJNoidHat of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "NoidHat", 
			pName: "Clothing",
			pIDName: "Noid's Hat",
			loop: 0,
			pBaseView: 32000,
			pAction: 29,
			pClutStart: 63,
			pColor: 58,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 10,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJRandomSewerNPC of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RandomSewerNPC", 
			pName: "<bad engrave>",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJRandomSewerNPCa of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "RandomSewerNPCa", 
			pName: "<bad engrave>",
			loop: 2,
			pBaseView: 100,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)

	)
)

(instance SOBJmwOdinsEdge of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwOdinsEdge", 
			pName: "Two Handed Sword",
			pIDName: "Odins Anger",
			loop: 0,
			pBaseView: 15500,
			pAction: 29,
			pClutStart: 29,
			pColor: 16,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 200,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 2,
		)
	)
)

(instance SOBJmwIronwoodCudgel of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwIronwoodCudgel", 
			pName: "Club",
			pIDName: "Ironwood Cudgel",
			loop: 0,
			pBaseView: 15550,
			pAction: 29,
			pClutStart: 29,
			pColor: 104,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 130,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 2,
		)
	)
)

(instance SOBJmwHarbringer of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwHarbringer", 
			pName: "Battle Axe",
			pIDName: "Harbringer of Doom",
			loop: 0,
			pBaseView: 15750,
			pAction: 29,
			pClutStart: 29,
			pColor: 93,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 230,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 1,
		)
	)
)

(instance SOBJmwGram of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwGram", 
			pName: "Two Handed Sword",
			pIDName: "Gram",
			loop: 0,
			pBaseView: 15050,
			pAction: 29,
			pClutStart: 29,
			pColor: 16,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 200,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 2,
		)
	)
)

(instance SOBJmwWyrd of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwWyrd", 
			pName: "Throwing Dagger",
			pIDName: "Wyrd Dagger",
			loop: 0,
			pBaseView: 15600,
			pAction: 29,
			pClutStart: 29,
			pColor: 16,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 0,
		)
	)
)

(instance SOBJmwEnidsNeedle of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwEnidsNeedle", 
			pName: "Throwing Dagger",
			pIDName: "Enid's Needle",
			loop: 0,
			pBaseView: 15650,
			pAction: 29,
			pClutStart: 29,
			pColor: 16,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 0,
		)
	)
)

(instance SOBJmwFafnirFang of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "mwFafnirFang", 
			pName: "Dagger",
			pIDName: "Fafnir Fang",
			loop: 0,
			pBaseView: 15450,
			pAction: 29,
			pClutStart: 29,
			pColor: 16,
			pBaseBitsLo: 513,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 300,
		)

		(aWhatObj addBase: BDescribed)

		((aWhatObj addBase: BWeapon)
			pDamageType: 0,
		)
	)
)

(instance SOBJBeanie of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Beanie", 
			pName: "Clothing",
			pIDName: "Beanie",
			loop: 0,
			pBaseView: 31450,
			pAction: 29,
			pClutStart: 63,
			pColor: -1,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 10,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 0,
			pMask: -1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJBikini of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Bikini", 
			pName: "Bikini",
			loop: 0,
			pBaseView: 10650,
			pAction: 29,
			pClutStart: 73,
			pColor: 100,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 6,
			pMask: -2,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSwimsuit of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Swimsuit", 
			pName: "Swimsuit",
			loop: 0,
			pBaseView: 10550,
			pAction: 29,
			pClutStart: 73,
			pColor: 100,
			pBaseBitsLo: 9,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 0,
			pWeight: 5,
		)

		((aWhatObj addBase: BWearable)
			pLayer: 0,
			pAreaWorn: 6,
			pMask: -3,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJLizard of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Lizard", 
			pName: "Lizard",
			loop: 2,
			pBaseView: 42500,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 10,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJSlime of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Slime", 
			pName: "Slime",
			loop: 2,
			pBaseView: 41700,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 10,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJBunny of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "Bunny", 
			pName: "Bunny",
			loop: 2,
			pBaseView: 42550,
			pAction: 1,
			pClutStart: 104,
			pColor: 104,
			pBaseBitsLo: 4162,
			pBaseBitsHi: 64,
			pSoundGroup: 10,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		(aWhatObj addBase: BCharacter)

		((aWhatObj addBase: BContainer)
			pWeightCap: 1400,
			pBulkCap: 2000,
		)

		(aWhatObj addBase: BNPC)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJHibiscusBlue of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "HibiscusBlue", 
			pName: "2018 Blue Hibiscus",
			loop: 0,
			pBaseView: 30151,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 1,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJHibiscusPink of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "HibiscusPink", 
			pName: "2018 Pink Hibiscus",
			loop: 0,
			pBaseView: 30152,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 1,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJHibiscusPurple of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "HibiscusPurple", 
			pName: "2018 Purple Hibiscus",
			loop: 0,
			pBaseView: 30153,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 1,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance SOBJHibiscusYellow of Code
	(properties
		name ""
	)

	(method (doit aWhatObj)
		(aWhatObj
			name: "HibiscusYellow", 
			pName: "2018 Yellow Hibiscus",
			loop: 0,
			pBaseView: 30158,
			pAction: 29,
			pClutStart: 0,
			pColor: 0,
			pBaseBitsLo: 1,
			pBaseBitsHi: 64,
		)

		(aWhatObj setAction: (aWhatObj pAction?))
		(if gWObjectLite (return))

		((aWhatObj addBase: BCarryable)
			pBulk: 1,
			pWeight: 1,
		)

		(aWhatObj addBase: BDescribed)
	)
)

(instance StockObjInitter7 of Code
	(method (doit)
		(StockObjList add: SOBJGreenCrystalD)
		(StockObjList add: SOBJGreenCrystalE)
		(StockObjList add: SOBJGreenCrystalF)
		(StockObjList add: SOBJGreenCrystalG)
		(StockObjList add: SOBJCellFloorA)
		(StockObjList add: SOBJCellFloorB)
		(StockObjList add: SOBJCellFloorC)
		(StockObjList add: SOBJCellFloorD)
		(StockObjList add: SOBJCellFloorE)
		(StockObjList add: SOBJCellFloorF)
		(StockObjList add: SOBJCellFloorG)
		(StockObjList add: SOBJCellFloorH)
		(StockObjList add: SOBJCellFloorI)
		(StockObjList add: SOBJGreenWaterA)
		(StockObjList add: SOBJGreenWaterB)
		(StockObjList add: SOBJGreenWaterC)
		(StockObjList add: SOBJGreenWaterD)
		(StockObjList add: SOBJLavaA)
		(StockObjList add: SOBJLavaB)
		(StockObjList add: SOBJLavaC)
		(StockObjList add: SOBJLavaD)
		(StockObjList add: SOBJLavaE)
		(StockObjList add: SOBJLavaF)
		(StockObjList add: SOBJLavaG)
		(StockObjList add: SOBJYellowShroomA)
		(StockObjList add: SOBJYellowShroomB)
		(StockObjList add: SOBJYellowShroomC)
		(StockObjList add: SOBJYellowShroomD)
		(StockObjList add: SOBJEnidStatue)
		(StockObjList add: SOBJDuachStatue)
		(StockObjList add: SOBJEnidBackArch)
		(StockObjList add: SOBJEnidBackDoor)
		(StockObjList add: SOBJDespothesStatue)
		(StockObjList add: SOBJElphameStatue)
		(StockObjList add: SOBJFinvarraStatue)
		(StockObjList add: SOBJMabonStatue)
		(StockObjList add: SOBJSentinelBaldric)
		(StockObjList add: SOBJImplementorBaldric)
		(StockObjList add: SOBJEventsBaldric)
		(StockObjList add: SOBJMentorBaldric)
		(StockObjList add: SOBJGameOfficial)
		(StockObjList add: SOBJSentinelHelm)
		(StockObjList add: SOBJMentorHelmet)
		(StockObjList add: SOBJBishopHat)
		(StockObjList add: SOBJDuachsAura)
		(StockObjList add: SOBJDespothesCrown)
		(StockObjList add: SOBJRareCrown)
		(StockObjList add: SOBJHairDye)
		(StockObjList add: SOBJhdLightRed)
		(StockObjList add: SOBJhdRed)
		(StockObjList add: SOBJhdLightGrey)
		(StockObjList add: SOBJhdGrey)
		(StockObjList add: SOBJhdDarkGrey)
		(StockObjList add: SOBJhdOrange)
		(StockObjList add: SOBJhdLightOrange)
		(StockObjList add: SOBJhdReddishBrown)
		(StockObjList add: SOBJhdBrown)
		(StockObjList add: SOBJhdLightYellow)
		(StockObjList add: SOBJhdYellow)
		(StockObjList add: SOBJhdLightBlue)
		(StockObjList add: SOBJhdBlue)
		(StockObjList add: SOBJhdWhite)
		(StockObjList add: SOBJhdOlive)
		(StockObjList add: SOBJhdLightOlive)
		(StockObjList add: SOBJhdMagenta)
		(StockObjList add: SOBJhdLightMagenta)
		(StockObjList add: SOBJhdDarkBrown)
		(StockObjList add: SOBJhdLightBrown)
		(StockObjList add: SOBJhdAqua)
		(StockObjList add: SOBJhdLightAqua)
		(StockObjList add: SOBJhdGreen)
		(StockObjList add: SOBJhdLightGreen)
		(StockObjList add: SOBJhdPurple)
		(StockObjList add: SOBJhdLightPurple)
		(StockObjList add: SOBJhdPaleBrown)
		(StockObjList add: SOBJhdPalePaleBrown)
		(StockObjList add: SOBJBaseDingo)
		(StockObjList add: SOBJDingoPup)
		(StockObjList add: SOBJCTCHorn)
		(StockObjList add: SOBJRibbon)
		(StockObjList add: SOBJBlueRibbon)
		(StockObjList add: SOBJRedRibbon)
		(StockObjList add: SOBJWhiteRibbon)
		(StockObjList add: SOBJGreenRibbon)
		(StockObjList add: SOBJYellowRibbon)
		(StockObjList add: SOBJGMCTCHorn)
		(StockObjList add: SOBJMistCreature)
		(StockObjList add: SOBJMistSpy)
		(StockObjList add: SOBJServant)
		(StockObjList add: SOBJApophis)
		(StockObjList add: SOBJBerserker)
		(StockObjList add: SOBJWizardNPC)
		(StockObjList add: SOBJWizardGuardNPC)
		(StockObjList add: SOBJEvilWizard)
		(StockObjList add: SOBJGoodWizard)
		(StockObjList add: SOBJNeutralWizard)
		(StockObjList add: SOBJEvilMinion)
		(StockObjList add: SOBJChampion)
		(StockObjList add: SOBJProtector)
		(StockObjList add: SOBJDireWolf)
		(StockObjList add: SOBJBerserkerMed)
		(StockObjList add: SOBJPaladin)
		(StockObjList add: SOBJPaladinA)
		(StockObjList add: SOBJPaladinB)
		(StockObjList add: SOBJBaseWarden)
		(StockObjList add: SOBJWardenHA06)
		(StockObjList add: SOBJWardenHA07)
		(StockObjList add: SOBJWardenHA08)
		(StockObjList add: SOBJWardenHA09)
		(StockObjList add: SOBJWardenHA10)
		(StockObjList add: SOBJWardenHA11)
		(StockObjList add: SOBJWardenHA12)
		(StockObjList add: SOBJSoldier)
		(StockObjList add: SOBJSoldierE)
		(StockObjList add: SOBJSoldierN)
		(StockObjList add: SOBJSoldierG)
		(StockObjList add: SOBJRandomMistGemD)
		(StockObjList add: SOBJRandomMistGemC)
		(StockObjList add: SOBJRandomMistGemB)
		(StockObjList add: SOBJRandomMistGemA)
		(StockObjList add: SOBJMinotaurTreasureB)
		(StockObjList add: SOBJMinotaurTreasureA)
		(StockObjList add: SOBJMinotaurGuard)
		(StockObjList add: SOBJMinotaurSoul)
		(StockObjList add: SOBJMinotaurSoulA)
		(StockObjList add: SOBJMinotaurSoulB)
		(StockObjList add: SOBJMinotaurSoulC)
		(StockObjList add: SOBJMinotaurSoulD)
		(StockObjList add: SOBJMinotaurSoulE)
		(StockObjList add: SOBJBaseMinotaur)
		(StockObjList add: SOBJMinotaurWarrior)
		(StockObjList add: SOBJMinotaurMage)
		(StockObjList add: SOBJMinotaurWarriorA)
		(StockObjList add: SOBJMinotaurWarriorB)
		(StockObjList add: SOBJMinotaurWarriorC)
		(StockObjList add: SOBJMinotaurWarriorD)
		(StockObjList add: SOBJMinotaurWarriorE)
		(StockObjList add: SOBJMinotaurMageA)
		(StockObjList add: SOBJMinotaurMageB)
		(StockObjList add: SOBJMinotaurMageC)
		(StockObjList add: SOBJMinotaurMageD)
		(StockObjList add: SOBJMinotaurMageE)
		(StockObjList add: SOBJSNSWeb1)
		(StockObjList add: SOBJSNSWeb2)
		(StockObjList add: SOBJSNSWeb3)
		(StockObjList add: SOBJSNSSkull)
		(StockObjList add: SOBJSNSAltar)
		(StockObjList add: SOBJSNSTorch)
		(StockObjList add: SOBJSNSFountain)
		(StockObjList add: SOBJSNSMushroom)
		(StockObjList add: SOBJSNSSittingRock)
		(StockObjList add: SOBJSNSStool)
		(StockObjList add: SOBJSNSChair)
		(StockObjList add: SOBJSNSStoneBench)
		(StockObjList add: SOBJSNSBasket)
		(StockObjList add: SOBJSNSDresser)
		(StockObjList add: SOBJSNSStorage)
		(StockObjList add: SOBJSNSCloset)
		(StockObjList add: SOBJSNSBigStrongBox)
		(StockObjList add: SOBJCopperShop)
		(StockObjList add: SOBJNoidHat)
		(StockObjList add: SOBJRandomSewerNPC)
		(StockObjList add: SOBJRandomSewerNPCa)
		(StockObjList add: SOBJmwOdinsEdge)
		(StockObjList add: SOBJmwIronwoodCudgel)
		(StockObjList add: SOBJmwHarbringer)
		(StockObjList add: SOBJmwGram)
		(StockObjList add: SOBJmwWyrd)
		(StockObjList add: SOBJmwEnidsNeedle)
		(StockObjList add: SOBJmwFafnirFang)
		(StockObjList add: SOBJBeanie)
		(StockObjList add: SOBJBikini)
		(StockObjList add: SOBJSwimsuit)
		(StockObjList add: SOBJLizard)
		(StockObjList add: SOBJSlime)
		(StockObjList add: SOBJBunny)
		(StockObjList add: SOBJHibiscusBlue)
		(StockObjList add: SOBJHibiscusPink)
		(StockObjList add: SOBJHibiscusPurple)
		(StockObjList add: SOBJHibiscusYellow)
	)
)
